[general]
import = ["~/.config/alacritty/themes/tokyonight.toml"]

[font]
size = 18
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[window]
startup_mode = "Maximized"
# opacity = 0.6
dynamic_padding = true

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"

